### ISSUE TITLE
Missing of raw data

### ISSUE THREAD

**Issue by M1stF0rest** [mm-graph-benchmark/mm-graph-benchmark#4]
Hi, thank you for your work! However, I encountered one problem when trying to reproduce your work: In your code of 'downloading the raw images', it required a file containing the url info of images used in the dataset, but this file is nowhere to be found in your GitHub or huggingface repositories. Do you mind uploading that file as well?

<img width="659" alt="截屏2024-07-25 下午3 41 47" src="https://github.com/user-attachments/assets/5971cf1b-2c08-4126-a559-015c58a36316">

**Comment by jwzhi** [comment]
Due to license issues, I won't be able to upload the raw data directly. You can find the raw data here: https://cseweb.ucsd.edu/~jmcauley/datasets.html#amazon_reviews. It has a files says item metadata. I have also uploaded the script to get the necessary raw data from the files. Let me know if you have any other questions. Thanks!

**Comment by M1stF0rest** [comment]
> Due to license issues, I won't be able to upload the raw data directly. You can find the raw data here: https://cseweb.ucsd.edu/~jmcauley/datasets.html#amazon_reviews. It has a files says item metadata. I have also uploaded the script to get the necessary raw data from the files. Let me know if you have any other questions. Thanks!

Hi, I did not find the scripts of 'getting necessary raw data' in this repository. Do you mind uploading them when you are available?

**Comment by jwzhi** [comment]
https://huggingface.co/datasets/mm-graph-org/mm-graph/tree/main/raw-data
